version: 2.1
executors:
  nuxt_node:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.8.0
jobs:
  deploy:
    executor:
      name: nuxt_node
    steps:
      - checkout
      # 依存関係のインストール
      - run:
          name: Install dependencies
          command: yarn install
      # Firebaseへのデプロイ
      - run:
          name: Build
          command: yarn build

      - run:
        name: Deploy to Firebase
        command: yarn deploy --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only: master